### ISSUE TITLE
Out of date personal site screenshot

### ISSUE THREAD

**Issue by adarsh** [venetucci/michelle.codes#24]
![michelle_codes_readme_md_at_master_ _venetucci_michelle_codes](https://cloud.githubusercontent.com/assets/913757/17541211/07b183c4-5e72-11e6-8bdb-dae4e20ef4bf.png)

I'd open the PR but I figured you'd want to take the new screenshot yourself.

**Comment by venetucci** [comment]
Thank you! Updated.
